# Generated by Django 3.0.7 on 2020-12-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20200618_2034"),
    ]

    operations = [
        migrations.AddField(
            model_name="post", name="draft", field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="headline",
            field=models.CharField(default=True, max_length=400),
            preserve_default=False,
        ),
    ]
