# Generated by Django 3.0.7 on 2020-12-22 19:28

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_auto_20201222_1911"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="post", managers=[("live_posts", django.db.models.manager.Manager()),],
        ),
        migrations.AlterField(
            model_name="post",
            name="headline",
            field=models.CharField(max_length=400, null=True),
        ),
    ]
