# Generated by Django 3.0.7 on 2020-12-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_auto_20201222_1928"),
    ]

    operations = [
        migrations.AlterModelManagers(name="post", managers=[],),
    ]
