# Generated by Django 3.0.7 on 2020-12-27 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_auto_20201227_2244"),
    ]

    operations = [
        migrations.AlterModelManagers(name="post", managers=[],),
    ]
