# Generated by Django 3.0.7 on 2021-01-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_auto_20201227_2254"),
    ]

    operations = [
        migrations.AddField(
            model_name="post", name="slug", field=models.SlugField(null=True),
        ),
    ]
